### ISSUE TITLE
Write Tests for FileSet class

### ISSUE THREAD

**Issue by codingvirtual** [codingvirtual/CSC478B#12]
Test cases for FileSet can now be started.

**Comment by ghost** [comment]
removePath() takes data type "File" as an argument, whereas the fileset arraylist is cast as String.  Any reason for the "File" data type on removePath?

**Comment by ghost** [comment]
Is the "Schedule" class ready to test?

**Comment by codingvirtual** [comment]
removePath should take a String now. And yes, Schedule is ready to test.

**Comment by codingvirtual** [comment]
right now, addPath should fail in that it will let you add the same path twice, which needs to be considered an error.
