### ISSUE TITLE
Change Default Destination to "Home" directory

### ISSUE THREAD

**Issue by codingvirtual** [codingvirtual/CSC478B#32]
Presently when the app opens, the default destination is not a valid path (more of a placeholder). Some default destination should be offered. Probably the "home" directory on whatever system the user is using. It's likely that there's a Java call you can make to get the home directory.

**Comment by ashley-robertson** [comment]
Fix is working on systems running Mac OS X and Windows 8.1. Further testing is needed for Windows 7.

**Comment by codingvirtual** [comment]
Closed with commit 0cd8c2c871dc035294842c362de7fd1199ff0d18 on 10/27/15

**Comment by codingvirtual** [comment]
closes #32
