### ISSUE TITLE
Develop FileSet Interface

### ISSUE THREAD

**Issue by codingvirtual** [codingvirtual/CSC478B#4]
Solidify the FileSet class so that we can continue design of the rest of the app, which will ultimately revolve around the definition of FileSet

**Comment by codingvirtual** [comment]
@zburch @ashley-robertson See my "TODO" questions inside the body of the FileSet code.

**Comment by ashley-robertson** [comment]
addPath(String path): It might be better to error-check all paths in a separate method (verifyFileSet( )?) just in case a user alters his/her local filesystem AFTER setting up the source list.
