### ISSUE TITLE
Manually editing destination path bypasses validation

### ISSUE THREAD

**Issue by codingvirtual** [codingvirtual/CSC478B#44]
If you manually type a path into the Destination input box (instead of using the Browse button), the entered path is not checked for validity. Need to add validation to that field when it loses focus (or if enter/return is pressed) OR don't allow direct entry into that field.

**Comment by ashley-robertson** [comment]
Closed with commit 71953de.

**Comment by codingvirtual** [comment]
NOTE: I am seeing an exception printed in the console so it appears the exception is being generated, but the UI isn't dealing with it
