### ISSUE TITLE
BUG - destination is reset to user.home

### ISSUE THREAD

**Issue by codingvirtual** [codingvirtual/CSC478B#53]
If the user chooses a destination other than their "home" directory (like the desktop), that setting is not preserved if they save, quit, and relaunch the app.

It appears that initComponents in UIViewController needs to check if there is a destination already set in the default file set and if so, display it (validation may need to occur as well).

**Comment by ashley-robertson** [comment]
Your saveDefaultFileSet( ) doesn't appear to save the destination (only the file set as the name suggests), so I'm not sure how to "check if there is a destination already set in the default file set"?

**Comment by codingvirtual** [comment]
I didn't write it well. Here's what I meant. If you set a destination, then hit save, then quit the program, then come back into it, it should "remember" the destination you just saved. Right now, it doesn't do that. In your initComponents() method, do you by chance check the fileSet to see if it has a destination and if so, preset the field in the UI to match? That's what I was referring to...

**Comment by codingvirtual** [comment]
Ashley,

The destination is a field in the FileSet. By saving the FileSet object, I’m saving not only all of the paths, but also the name of the backup and the destination.

On Nov 19, 2015, at 4:21 PM, ashley-robertson notifications@github.com wrote:

Your saveDefaultFileSet( ) doesn't appear to save the destination (only the file set as the name suggests), so I'm not sure how to "check if there is a destination already set in the default file set"?
