### ISSUE TITLE
Preferred format for path list from FileSet?

### ISSUE THREAD

**Issue by codingvirtual** [codingvirtual/CSC478B#8]
@ashley-robertson I would like to create a method in FileSet that you can easily call to get the list of paths in the FileSet. Let me know what return type that method should have (do you want a straight array, an ArrayList, etc.).

The reason for the ask is to try to make it easier on you to take the result of that call and stuff it into the list of what is being backed up that is displayed in the UI.

Relates to:
#4
#5

**Comment by ashley-robertson** [comment]
I would prefer an ArrayList<String> for easier element access/manipulation (e.g. sorting the files/folders alphabetically with Collections.sort( )).

See also: http://eclipsesource.com/blogs/2014/04/11/3-good-reasons-to-avoid-arrays-in-java-interfaces/

**Comment by codingvirtual** [comment]
Ok perfect - consider it done! Also, I am going to limit this first version to working ONLY with files, not folders, so as you code the UI you can use a file chooser that forces the user to pick a file and not a folder. We'll make folder support a future

**Comment by codingvirtual** [comment]
Ok sounds good - consider it done.
